AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PhenoBerry - Infraestructura Nativa AWS (SageMaker + S3 + DynamoDB)

Parameters:
  EnvName:
    Type: String
    Default: dev
    Description: Nombre del ambiente (dev, prod)

Resources:
  # ==========================================
  # 1. DATA LAKE (S3 BUCKETS)
  # ==========================================
  S3RawZone:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "phenoberry-${EnvName}-raw-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

  S3ProcessedZone:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "phenoberry-${EnvName}-processed-${AWS::AccountId}"

  S3ModelArtifacts:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "phenoberry-${EnvName}-artifacts-${AWS::AccountId}"

  S3FinalOutput:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "phenoberry-${EnvName}-output-${AWS::AccountId}"

  # ==========================================
  # 2. METADATA STORE (DYNAMODB)
  # ==========================================
  DynamoDBTrackingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "phenoberry-${EnvName}-tracking"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: media_id
          AttributeType: S
      KeySchema:
        - AttributeName: media_id
          KeyType: HASH

  # ==========================================
  # 3. LAMBDA: TILING (DOCKER) - PROCESA INFERENCIA
  # ==========================================
  TilingProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
      Timeout: 300
      Environment:
        Variables:
          PROCESSED_BUCKET: !Ref S3ProcessedZone
          DYNAMO_TABLE: !Ref DynamoDBTrackingTable
      Events:
        UploadJPG:
          Type: S3
          Properties:
            Bucket: !Ref S3RawZone
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
                  - Name: suffix
                    Value: .jpg
        UploadPNG:
          Type: S3
          Properties:
            Bucket: !Ref S3RawZone
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
                  - Name: suffix
                    Value: .png
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "phenoberry-${EnvName}-raw-${AWS::AccountId}"
        - S3CrudPolicy:
            BucketName: !Ref S3ProcessedZone
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTrackingTable
    Metadata:
      DockerTag: python3.11-v1
      DockerContext: ..
      Dockerfile: docker/processing_image/Dockerfile

  # ==========================================
  # 4. SAGEMAKER: ROL DE EJECUCIÓN (EL QUE ENTRENA)
  # ==========================================
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  # ==========================================
  # 5. LAMBDA: DISPARADOR DE ENTRENAMIENTO (BRIDGE)
  # ==========================================
  SageMakerTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/aws_lambda/sagemaker_trigger/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Environment:
        Variables:
          SAGEMAKER_ROLE_ARN: !GetAtt SageMakerExecutionRole.Arn
          RAW_BUCKET: !Sub "phenoberry-${EnvName}-raw-${AWS::AccountId}"
          ARTIFACTS_BUCKET: !Ref S3ModelArtifacts # Este no causa círculo porque no dispara la función
      Policies:
        - AmazonSageMakerFullAccess
        - S3ReadPolicy: # Agregamos permiso explícito de lectura al raw
            BucketName: !Sub "phenoberry-${EnvName}-raw-${AWS::AccountId}"
        - Statement:
            - Effect: Allow
              Action: iam:PassRole
              Resource: !GetAtt SageMakerExecutionRole.Arn
              Condition:
                StringEquals:
                  iam:PassedToService: sagemaker.amazonaws.com
      Events:
        NewTrainingData:
          Type: S3
          Properties:
            Bucket: !Ref S3RawZone
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .zip

  InferenceLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image  # <-- Cambiar de Zip a Image
      FunctionName: inference-lambda
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          PROCESSED_BUCKET: !Sub "phenoberry-${EnvName}-processed-${AWS::AccountId}"
          OUTPUT_BUCKET: !Ref S3FinalOutput
          MODEL_BUCKET: "phenoberry-dev-artifacts-038876987034"
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "phenoberry-${EnvName}-processed-${AWS::AccountId}"
        - S3WritePolicy:
            BucketName: !Ref S3FinalOutput
        - S3ReadPolicy:
            BucketName: "phenoberry-dev-artifacts-038876987034"
      Events:
        TilesUpload:
          Type: S3
          Properties:
            Bucket: !Ref S3ProcessedZone
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: tiles/
    Metadata:
      Dockerfile: docker/inference_yolo/Dockerfile
      DockerContext: ..
      DockerTag: python3.11-v1

Outputs:
  RawBucketName:
    Value: !Ref S3RawZone
  ArtifactsBucket:
    Value: !Ref S3ModelArtifacts